apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: devacr83.azurecr.io/python-repo/django-app:latest
        ports:
        - containerPort: 8000
---
---
apiVersion: v1
kind: Service
metadata:
  name: django-app
  labels:
    run: django-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    run: django-app        
           

