apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-deployment
  labels:
    app: django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: devacr83.azurecr.io/python-repo/django-app:latest
        ports:
        - containerPort: 8080
           
<<<<<<< HEAD
          
=======

>>>>>>> c8f8a2be26eb22257a2b255ed7e0ba258803357a
